# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200, verbose_name='Имя персонажа')),
                ('sex', models.CharField(choices=[('Y', 'Мальчик'), ('N', 'Девочка'), ('X', 'Оно')], max_length=200, verbose_name='Пол')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='Аватар')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('approved', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=200, verbose_name='Одобрено')),
            ],
            options={
                'verbose_name_plural': 'персонажи',
                'verbose_name': 'Персонаж',
            },
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='От кого')),
                ('from_adr', models.CharField(max_length=200, verbose_name='От кого')),
                ('to_adr', models.CharField(max_length=200, verbose_name='Кому')),
                ('departure', models.DateTimeField(verbose_name='date published')),
                ('arrival', models.DateTimeField(verbose_name='date published')),
                ('owl_id', models.IntegerField()),
                ('reading_time', models.DateTimeField(verbose_name='date published')),
                ('message', models.CharField(max_length=1000, verbose_name='От кого')),
            ],
            options={
                'verbose_name_plural': 'письма',
                'verbose_name': 'Письмо',
            },
        ),
        migrations.CreateModel(
            name='Owls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя совы')),
                ('where_now', models.CharField(max_length=200, verbose_name='У кого находится')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='Аватар')),
                ('master', models.IntegerField()),
                ('end_point', models.DateTimeField(verbose_name='date published')),
                ('message', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'совы',
                'verbose_name': 'Сова',
            },
        ),
    ]
