# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owls',
            old_name='end_point',
            new_name='time_to',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 30, 14, 13, 34, 915971), verbose_name='date published'),
        ),
    ]
