# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0004_auto_20161209_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='message',
            field=models.CharField(max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 20, 54, 25, 880367, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 21, 54, 25, 880397, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
