# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0006_auto_20171030_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testform',
            options={'verbose_name': 'Тестовая форма', 'verbose_name_plural': 'тестовые формы'},
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 23, 22, 20, 662656, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 0, 22, 20, 662687, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
