# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0010_auto_20171031_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='field2',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 2, 4, 36, 894829, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 3, 4, 36, 894859, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
