# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 00:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0014_auto_20171113_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='from_adr',
        ),
        migrations.RemoveField(
            model_name='letters',
            name='owl_id',
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 0, 5, 14, 557168, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 1, 5, 14, 557199, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
