# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 00:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0015_auto_20171114_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='message',
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 0, 10, 12, 628761, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 1, 10, 12, 628792, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
