# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0016_auto_20171114_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='message',
            field=models.CharField(default='SOME STRING', max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 17, 38, 48, 977879, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 18, 38, 48, 977908, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
