# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0017_auto_20171114_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='message',
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 21, 47, 43, 711433, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 22, 47, 43, 711478, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
