# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alltables', '0018_auto_20171117_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='send_to2',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 21, 50, 27, 105686, tzinfo=utc), verbose_name='Время вылета совы'),
        ),
        migrations.AlterField(
            model_name='owls',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 22, 50, 27, 105727, tzinfo=utc), verbose_name='Время прилета совы'),
        ),
    ]
